const modData = {
    "@title": "Generated by ChatGPT",
    "@description": "AI-generated modifications",
};

const tableData = {};
const chatBox = document.getElementById("chatBox");
const jsonDisplay = document.getElementById("jsonDisplay");

document.addEventListener("DOMContentLoaded", () => {
    fetchRowsAndColumns();
    fetchAPIKey();
});

// Fetch and Decrypt API Key
let apiKey = "";

function fetchAPIKey() {
    fetch('data/api_key.json')  // Path to your JSON file
        .then(response => response.json())
        .then(data => {
            const encryptedKey = data.encryptedKey;
            apiKey = decryptAPIKey(encryptedKey, 'your_secret_passphrase');
            appendAIMessage("Hello");
        })
        .catch(error => {
            console.error("Error fetching the API key:", error);
            appendAIMessage("Failed to fetch or decrypt the API key.");
        });
}

function decryptAPIKey(encryptedKey, passphrase) {
    const crypto = window.crypto || window.msCrypto;  // for IE11
    const algorithm = 'AES-CBC';
    
    // Base64 decode the encrypted key and the IV
    const iv = encryptedKey.slice(0, 16);  // First 16 bytes are IV
    const encrypted = encryptedKey.slice(16);

    const key = crypto.subtle.importKey(
        "raw",
        new TextEncoder().encode(passphrase),
        { name: "AES-CBC" },
        false,
        ["decrypt"]
    );

    return key.then(function (cryptoKey) {
        const ivBuffer = new TextEncoder().encode(iv);
        const encryptedBuffer = new TextEncoder().encode(encrypted);
        
        return crypto.subtle.decrypt(
            { name: algorithm, iv: ivBuffer },
            cryptoKey,
            encryptedBuffer
        ).then(function (decrypted) {
            const decoder = new TextDecoder();
            return decoder.decode(decrypted);
        });
    });
}

// Example: Fetching rows and columns
function fetchRowsAndColumns() {
    fetch("data/rows_columns.txt")
        .then(response => response.text())
        .then(data => {
            const lines = data.split("\n").map(line => line.trim()).filter(line => line);
            let currentTable = null;

            lines.forEach(line => {
                if (line.includes(" rows:")) {
                    const [table, rows] = line.split(" rows:").map(item => item.trim());
                    currentTable = table;
                    tableData[currentTable] = { rows: rows.split(",").map(row => row.trim()), columns: [] };
                } else if (line.includes(" Column Names:")) {
                    const [table, columns] = line.split(" Column Names:").map(item => item.trim());
                    if (currentTable === table && tableData[currentTable]) {
                        tableData[currentTable].columns = columns.split(",").map(col => col.trim());
                    }
                }
            });

            appendAIMessage("I have loaded the tables, rows, and columns from the file. You can now ask me to modify the JSON.");
        })
        .catch(error => console.error("Error fetching rows and columns:", error));
}

function appendUserMessage(message) {
    const div = document.createElement("div");
    div.className = "user";
    div.textContent = message;
    chatBox.appendChild(div);
    chatBox.scrollTop = chatBox.scrollHeight;
}

function appendAIMessage(message) {
    const div = document.createElement("div");
    div.className = "ai";
    div.textContent = message;
    chatBox.appendChild(div);
    chatBox.scrollTop = chatBox.scrollHeight;
}

async function sendMessage() {
    const userInput = document.getElementById("userInput").value.trim();
    if (!userInput) return;

    appendUserMessage(userInput);
    document.getElementById("userInput").value = "";

    const systemPrompt = `
You are a JSON builder assistant. You will process user requests to modify JSON data. 
Here are the available tables, rows, and columns: ${JSON.stringify(tableData)}.
You must validate the user's input and provide valid JSON modifications. If a request is unclear, ask for clarification.
`;

    const chatResponse = await fetchChatGPTResponse(systemPrompt, userInput);
    if (chatResponse.error) {
        appendAIMessage("Error: Unable to process your request.");
    } else {
        appendAIMessage(chatResponse.message);
        try {
            const modifications = JSON.parse(chatResponse.json);
            Object.assign(modData, modifications);
            updateJSONDisplay();
        } catch (error) {
            appendAIMessage("Error parsing the response JSON.");
        }
    }
}

async function fetchChatGPTResponse(systemPrompt, userInput) {
    const apiUrl = "https://api.openai.com/v1/completions";

    const messages = [
        { role: "system", content: systemPrompt },
        { role: "user", content: userInput },
    ];

    try {
        const response = await fetch(apiUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
                model: "gpt-3.5-turbo", // Change to "gpt-3.5-turbo" if gpt-4 is unavailable
                messages: messages,
            }),
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error("Error response:", errorData);
            document.getElementById("errorMessage").textContent = `Error: ${errorData.error.message}`;
            return { error: true };
        }

        const data = await response.json();
        if (data.choices && data.choices.length > 0) {
            return {
                message: data.choices[0].message.content,
                json: data.choices[0].message.content,
            };
        } else {
            document.getElementById("errorMessage").textContent = "No choices in response.";
            return { error: true };
        }
    } catch (error) {
        console.error("Error fetching ChatGPT response:", error);
        document.getElementById("errorMessage").textContent = `Error: ${error.message}`;
        return { error: true };
    }
}

function updateJSONDisplay() {
    jsonDisplay.textContent = JSON.stringify(modData, null, 4);
}
